[build]
  command = "npm run production"
  publish = "dist"

[[redirects]]
  from = "/blog"
  to = "/"

[[redirects]]  
  from = "/blog/*"
  to = "/posts/:splat"  

[[redirects]]  
  from = "/en/*"
  to = "/:splat" 

[[redirects]]  
  from = "/nl/*"
  to = "/:splat" 